USE [master]
GO

/****** Object:  Database [SignalRChatDB]    Script Date: 19.08.2020 12:56:23 ******/
CREATE DATABASE [SignalRChatDB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'SignalRChatDB', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\SignalRChatDB.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'SignalRChatDB_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\SignalRChatDB_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [SignalRChatDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

USE [SignalRChatDB];

CREATE TABLE [dbo].[Message] (
    [Id]          INT            IDENTITY (1, 1) NOT NULL,
    [User]        NVARCHAR (MAX) NULL,
    [Text]        NVARCHAR (MAX) NULL,
    [SendDate] DATETIME2 (7)  NOT NULL,
    [Receiver]    NVARCHAR (MAX) NULL,
    CONSTRAINT [PK_Message] PRIMARY KEY CLUSTERED ([Id] ASC)
);

CREATE TABLE [dbo].[AppUser] (
    [Id]          INT            IDENTITY (1, 1) NOT NULL,
    [Username]        NVARCHAR (MAX) NULL,
    [Password]        NVARCHAR (MAX) NULL,
    [ConnectionId]    NVARCHAR (MAX)  NOT NULL,
    CONSTRAINT [PK_AppUser] PRIMARY KEY CLUSTERED ([Id] ASC)
);


DROP TABLE [dbo].[Message]

ALTER DATABASE [SignalRChatDB] SET ENABLE_BROKER;

SELECT [name], [service_broker_guid], [is_broker_enabled]
FROM [master].[sys].[databases];

DROP DATABASE [SignalRChatDB];

ALTER DATABASE [SignalRChatDB] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [SignalRChatDB] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [SignalRChatDB] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [SignalRChatDB] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [SignalRChatDB] SET ARITHABORT OFF 
GO

ALTER DATABASE [SignalRChatDB] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [SignalRChatDB] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [SignalRChatDB] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [SignalRChatDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [SignalRChatDB] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [SignalRChatDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [SignalRChatDB] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [SignalRChatDB] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [SignalRChatDB] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [SignalRChatDB] SET  DISABLE_BROKER 
GO

ALTER DATABASE [SignalRChatDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [SignalRChatDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [SignalRChatDB] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [SignalRChatDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [SignalRChatDB] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [SignalRChatDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [SignalRChatDB] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [SignalRChatDB] SET RECOVERY FULL 
GO

ALTER DATABASE [SignalRChatDB] SET  MULTI_USER 
GO

ALTER DATABASE [SignalRChatDB] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [SignalRChatDB] SET DB_CHAINING OFF 
GO

ALTER DATABASE [SignalRChatDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [SignalRChatDB] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [SignalRChatDB] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [SignalRChatDB] SET QUERY_STORE = OFF
GO

ALTER DATABASE [SignalRChatDB] SET  READ_WRITE 
GO


